name: build_image
on:
  push:
    branches:
      - 'test'
jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install doublecmd -y -s .
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push --source https://www.myget.org/F/public-choco-dev/api/v2/package -k=${{ secrets.MYGET_API_KEY }}

